 INSERT INTO [dbo].[ALIASES]
 (ALIAS,ALIASTYPE,PASSWORD,USERNAME,ARCALIAS,ARCNAME,ID,SQLENGINE,AUTOLOGIN)
 VALUES
 ( 'STB CORE Data','$(sqltype)','7088ED8B04A4DC35','sa',NULL,NULL,2,'SQLSERVER',1);
 GO
 INSERT INTO [dbo].[ALIASES]
 (ALIAS,ALIASTYPE,PASSWORD,USERNAME,ARCALIAS,ARCNAME,ID,SQLENGINE,AUTOLOGIN)
 VALUES
 ('STB Software','STANDARD','','',NULL,NULL,3,'',0);
 GO
 INSERT INTO [dbo].[ALIASES]
 (ALIAS,ALIASTYPE,PASSWORD,USERNAME,ARCALIAS,ARCNAME,ID,SQLENGINE,AUTOLOGIN)
 VALUES
 ('STB Temp','STANDARD','','',NULL,	NULL,5,'',0);
 GO
 INSERT INTO [dbo].[ALIASES]
 (ALIAS,ALIASTYPE,PASSWORD,USERNAME,ARCALIAS,ARCNAME,ID,SQLENGINE,AUTOLOGIN)
 VALUES
 ( 'STB Work','$(sqltype)','7088ED8B04A4DC35','sa',NULL,NULL,6,'SQLSERVER',1);
GO
 INSERT INTO [dbo].[ALIASES]
 (ALIAS,ALIASTYPE,PASSWORD,USERNAME,ARCALIAS,ARCNAME,ID,SQLENGINE,AUTOLOGIN)
 VALUES
 ( 'STB System','$(sqltype)','7088ED8B04A4DC35','sa',NULL,NULL,7,'SQLSERVER',1);
 